import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button, Form, Input } from 'antd';
import Link from 'next/link';
import { useDispatch } from 'react-redux/es/exports';
import { registerRequest } from '@/saga/action';
import { useRouter } from 'next/router';

export default function Signup() {
  const dispatch = useDispatch()
  const router = useRouter()

  const onFinish = (values: any) => {
    console.log('Success:', values);
    dispatch(registerRequest({
      email: values.Email,
      password: values.password,
      username: values.username,
      callback: () =>{
        return router.push('/signin')
      }
    }))
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log('Failed:', errorInfo);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.login__block}>
          <h1 className={styles.title__signup}>Register</h1>
          <Form
            name="basic"
            labelCol={{ span: 8 }}
            wrapperCol={{ span: 16 }}
            style={{ maxWidth: 600 }}
            className={styles.form}
            initialValues={{ remember: true }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <Form.Item
            className={styles.input}
              name="username"
              rules={[{ required: true, message: 'Please input your username!' }]}
            >
              <Input className={styles.input}  placeholder="Username"/>
            </Form.Item>

            <Form.Item
            className={styles.input}
              name="password"
              rules={[{ required: true, message: 'Please input your password!' }]}
            >
              <Input.Password  className={styles.input}  placeholder="Password"/>
            </Form.Item>

            <Form.Item
              // label="Email"
              name="Email"
              rules={[{ required: true, type: "email", message: 'The input is not valid E-mail!' }]}
            >
              <Input className={styles.input}  placeholder="Email"/>
            </Form.Item>
           
            <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
              <Button type="primary" htmlType="submit">
                Sign Up
              </Button>
              <Link href={'./signin'}> <p className={styles.p}>Đã có tài khoản</p></Link>
            </Form.Item>
          </Form>

        </div>
      </main>
    </>
  )
}
