import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button, Avatar } from 'antd';
import { Layout } from 'antd';
import Link from 'next/link';
import Cookies from 'js-cookie'
import { useEffect } from 'react';
import { useRouter } from 'next/router';
const { Header, Footer, Sider, Content } = Layout;

export default function Home() {
const username = Cookies.get('todo-username')
const router = useRouter()

  useEffect(()=>{
    const token = Cookies.get('cookie-todo')
    if(token){
        router.push('/dashboard')
    }
  }, [])

  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Layout>
          <Header className={styles.headerStyle}>
            {username ? <Link href={'/test'}><h1>Dashboard</h1></Link> : <h1>Home</h1>}
            {username ? <div className={styles.home__avatar}>
              <Avatar style={{ backgroundColor: '#fde3cf', color: '#f56a00' }}>{username[0].toUpperCase()}</Avatar>
              <h3 className={styles.home__username}>{username}</h3>
            </div> : <Link href={'/signin'}>
              <Button>Login</Button></Link>}
          </Header>
          <Content className={styles.contentStyle}>
          </Content>
        </Layout>
      </div>
    </>
  )
}
