import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Avatar } from 'antd';
import { Layout, Space } from 'antd';
import Link from 'next/link';
import Cookies from 'js-cookie'


const { Header, Footer, Sider, Content } = Layout;

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const headerStyle: React.CSSProperties = {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: '#fff',
    height: 64,
    paddingInline: 50,
    lineHeight: '64px',
    backgroundColor: '#7dbcea',
  };

  const contentStyle: React.CSSProperties = {
    textAlign: 'center',
    height: 'calc(100vh - 64px)',
    color: '#fff',
    backgroundColor: '#ccc',
  };

  const username = Cookies.get('todo-username')



  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Layout>
          <Header style={headerStyle}>
            {username ? <Link href={'/test'}><h1>Dashboard</h1></Link> : <h1>Home</h1>}
            {username ? <div className={styles.home__avatar}>
              <Avatar style={{ backgroundColor: '#fde3cf', color: '#f56a00' }}>{username[0].toUpperCase()}</Avatar>
              <h3 className={styles.home__username}>{username}</h3>
            </div> : <Link href={'/signin'}>
              <Button>Login</Button></Link>}
          </Header>
          <Content style={contentStyle}>
          </Content>
        </Layout>
      </div>
    </>
  )
}
